### PR TITLE
Refactored based on review for Pull Request #4

### PR DESCRIPTION
**Pull request by tomzacchia**

### CODE REVIEW

**Comment by tomzacchia** [comment]
@uche-inyama  Why are not permitted to create another feature branch? I allows us to further isolate the codebase from any undesirable code that might break the application. Additionally we only request code reviews when merging dev to master.

**Comment by uche-inyama** [comment]
I can see you are creating several feature branches and then merge to dev, but for this project, you are to follow github flow. This is the instruction on pathwright. :point_down: **Take note of the last sentence**

``` Create a Pull Request from the feature-branch branch (give it a descriptive name that shortly says what this branch includes, e.g. homepage) to the master branch. We assume that this entire project is one feature for learning purposes.```

**Comment by tomzacchia** [comment]
@uche-inyama we made changes based on your comment, ref: ca9baf66b771c7f009b95c6e06f40484adf3acac

**Comment by tomzacchia** [comment]
@stratospherique we added the technologies used, however some of the other points that were mentioned were already previously added to the readme (https://github.com/tomzacchia/youtube_simple_clone/blob/master/README.md)

**Pull request merged**
